### PR TITLE
v0.0.5

### LINKED ISSUE #29: Edit Town Button
+ Edit Town
+ Edit a lot, Build Buy Mode
+ Is blue
+ Make pink

image

### LINKED ISSUE #33: Social Groups -- Jock Blue
+ jock still blue
+ post v0.0.4
+ revert to orange

image

### LINKED ISSUE #36: Create A Plumbot Buttons
+ create a plumbot
+ blue when male, pink when female
+ change to blue active

image

### LINKED ISSUE #39: Party Planner Balloons
+ Throw Party
+ Party Planner Balloons are pink
+ Revert back to original

image

### PR DESCRIPTION
**Pull request by aecyia**

### CODE REVIEW

**Comment by aecyia** [comment]
image

**Comment by aecyia** [comment]
S3_2F7D0004_00000000_DAA94B7D05E24532_puck_modes_mapview_normal_r2%%+IMAGS3_2F7D0004_00000000_ACF9B705D1404CF2_puck_modes_mapview_di_r2%%+IMAGS3_2F7D0004_00000000_12E4A5AF760DC703_puck_modes_mapview_active_r2%%+IMAGS3_2F7D0004_00000000_8D5706A0DB23F94E_puck_modes_mapview_hi_r2%%+IMAG

puck_modes_mapview

image

**Comment by aecyia** [comment]
image

**Comment by aecyia** [comment]
image

**Comment by VMPYRC** [comment]
# Changes

+ Edit Town Button
	+ ORIGINAL -- Blue
	+ CHANGE -- Pink
+ Create a Plumbot Buttons
	+ ORIGINAL -- Blue for male, Pink for female
	+ CHANGE -- Pink and White
+ Party Planner Balloons are colourful
	+ ORIGINAL -- No longer pink
	+ CHANGE -- Back to original
+ Various Minor Fixes
	+ Jock is Orange again
	+ Removed EP11_ANN_Robot_Traits

**Review by VMPYRC — APPROVED** [review]

**Comment by VMPYRC** [comment]
# Changes

+ Adventure Journal AND Scrapbook
	+ Background is now white
+ Create a Plumbot Buttons
	+ ORIGINAL -- Blue for male, Pink for female
	+ CHANGE -- Pink and White
+ Edit Town Button
	+ ORIGINAL -- Blue
	+ CHANGE -- Pink
+ Party Planner Balloons are colourful
	+ ORIGINAL -- No longer pink
	+ CHANGE -- Back to original
+ Various Minor Fixes
	+ Jock is Orange again
	+ Removed EP11_ANN_Robot_Traits

**Pull request merged**
