### PR TITLE
v0.0.7

### PR DESCRIPTION
**Pull request by VMPYRC**

### CODE REVIEW

**Comment by VMPYRC** [comment]
# Blue Buttons for Modes 

Blue Buttons for Modes

**Comment by VMPYRC** [comment]
# Blog App Rework 

- Recoloured icons
- Reset some back to the original
- Added a sakura icon to blog backgrounds 🌸
- Recoloured blog backgrounds
  - Base Game Colours:
    - Personal (Green, Smiley Face)
    - Review (Red, Film Reel)
    - News (Blue, Newspaper)
  - Now, it is:
    - Personal (Pink)
    - Review (Purple)
    - News (Blue)

## Make A New Blog
Make A New Blog

## Blog Types

### Review Blog
Review Blog

### News Blog
News Blog

### Personal Blog
Personal Blog

## Photos

### Landscape
Photo_Landscape

## Portrait
Photo_Portrait

## Sell A Blog Icon
Sell A Blog Icon

## Write a Post
Write a Post

**Comment by VMPYRC** [comment]
# Less Saturation

- Less Saturation for some files
- Gift Open Popup (Care package and mystery gift) has the yellow and green gift box back


S3_2F7D0004_00000000_65D880B56B9D1DF8_ATLAS_MysteryGiftOpenedPopup_00%%+IMAG
S3_2F7D0004_00000000_9FE33A38520B80D4_ATLAS_CarePackageOpenedPopup_00%%+IMAG

**Comment by VMPYRC** [comment]
# Less purple scrapbook

|v0.0.6|v0.0.7|
|-|-|
|S3_2F7D0004_00000000_CFC42FBB30B1637F_ATLAS_HUDScrapbook_00__+IMAG|S3_2F7D0004_00000000_CFC42FBB30B1637F_ATLAS_HUDScrapbook_00%%+IMAG|

## In Game

2024_October_01_Tuesday_01_54_53_240_PM
2024_October_01_Tuesday_01_55_41_818_PM
2024_October_01_Tuesday_01_56_13_302_PM

**Comment by VMPYRC** [comment]
# Fix Palette Icon

| Original | v0.0.7 |
| -------- | ------ |
|  image        |   image|

# I created a new icon for it called RainbowTetrisPalette

Image File:

RainbowTetrisPalette

Larger View on a black background:

2024_October_01_Tuesday_12_13_11_076_PM

## In Game

2024_October_01_Tuesday_05_40_16_911_PM

**Comment by VMPYRC** [comment]
# Tattoo Button is now purple



| Original | v0.0.6 | v0.0.7 |
| -------- | ------ | ------ |
|    2024_October_01_Tuesday_01_08_19_322_PM|  2024_October_01_Tuesday_01_08_38_405_PM      |   2024_October_01_Tuesday_01_07_07_588_PM     |

## In Game

| Note | In-Game |
| -------- | ------ |
|None Selected|2024_October_01_Tuesday_01_47_15_196_PM|
|Selected the star tattoo|2024_October_01_Tuesday_01_47_52_923_PM|
|Faded purple as you select the tattoo placement|2024_October_01_Tuesday_01_51_51_993_PM|

**Comment by VMPYRC** [comment]
# Scrapbook Rework

- Memory stamps
  - Original texture
  - Colourized to pink, blue, purple
- Replaced backgrounds of Positive/Neutral/Negative memories
- Purple Scrollbars

# In Game

## Memories
2024_October_01_Tuesday_05_03_25_826_PM

## Statistics

2024_October_01_Tuesday_05_04_51_887_PM

## Biography

2024_October_01_Tuesday_05_05_04_913_PM


## Positive
2024_October_01_Tuesday_05_03_39_556_PM
## Neutral
2024_October_01_Tuesday_05_04_00_539_PM
## Negative
2024_October_01_Tuesday_05_03_49_116_PM

**Review by aecyia — APPROVED** [review]

**Comment by aecyia** [comment]
# Changes

- Project Changes
  - Organized files
- Buttons for Modes (Live, Buy, Build)
  - Blue on active mode
  - Blue on hover
- Blog App
  - Recoloured icons
  - Reset some back to the original
  - Added a sakura icon to blog backgrounds 🌸
  - Recoloured blog backgrounds
    - Base Game Colours:
      - Personal (Green, Smiley Face)
      - Review (Red, Film Reel)
      - News (Blue, Newspaper)
    - Now, it is:
        - Personal (Pink)
        - Review (Purple)
        - News (Blue)
- Gift Open Popup
  - Care package, mystery gift
  - Brought back the yellow and green gift box, confetti
- Memories Scrapbook
  - Memory stamps
    - Original texture
    - Colourized to pink, blue, purple
  - Edit Memories
    - Custom backgrounds for Positive, Neutral, Negative 
  - Scrollbars became purple
- Palette icon
  - Created a new palette icon for Create a Sim >> Create a Style
- Tattoo Button
  - Became purple
- Minor Fixes
  - Updated Map Tag Icons
  - Less saturation for files that were dark pink

**Pull request merged**
